function Footer() {
  return (
    <footer className='py-5'>
      <p>
        <b>*</b>: These are dummy data generated by AI for example purposes.
      </p>
      <p>
        <b>**</b>: These data are examples and do not accurately reflect my
        actual skills.
      </p>
    </footer>
  )
}

export default Footer
